on:
  pull_request_target:
    paths:
      - "src/**/*"


jobs:
  tsc:
    name: Typescript Compile Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node 12
      uses: actions/setup-node@v2
      with:
        node-version: 12
    - name: npm install
      run: npm install
    - name: tsc
      uses: icrawl/action-tsc@v1